<wsdl:definitions targetNamespace="http://epolsoft.com/sv_conf">
    <wsdl:types>
        <xs:schema elementFormDefault="qualified" targetNamespace="http://epolsoft.com/sv_conf">
            <!--    Find all svConfs-->
            <xs:element name="getAllSvConfRequest">
                <xs:complexType>
                    <xs:sequence> </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="getAllSvConfResponse">
                <xs:complexType>
                </xs:complexType>
            </xs:element>
            <!--    Find svConf by name-->
            <xs:element name="getSvConfByNameRequest">
            </xs:element>
            <xs:element name="getSvConfByNameResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="svConf" type="sv:svConf"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <!--    Add svConf-->
            <xs:element name="addSvConfRequest">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="svConf" type="sv:svConf"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <!--    Update svConf-->
            <xs:element name="updateSvConfRequest">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="svConf" type="sv:svConf"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <!-- Delete svConf by name-->
            <xs:element name="deleteSvConfRequest">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="name" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <!--    Object svConf-->
            <xs:complexType name="svConf">
                <xs:sequence>
                    <xs:element name="name" type="xs:string">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="([a-zA-Z_]*)"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="value" type="xs:string"/>
                    <xs:element name="desc" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="updateSvConfRequest">
        <wsdl:part element="tns:updateSvConfRequest" name="updateSvConfRequest"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="getAllSvConfRequest">
        <wsdl:part element="tns:getAllSvConfRequest" name="getAllSvConfRequest"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="deleteSvConfRequest">
        <wsdl:part element="tns:deleteSvConfRequest" name="deleteSvConfRequest"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="getSvConfByNameResponse">
        <wsdl:part element="tns:getSvConfByNameResponse" name="getSvConfByNameResponse"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="addSvConfRequest">
        <wsdl:part element="tns:addSvConfRequest" name="addSvConfRequest"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="getSvConfByNameRequest">
        <wsdl:part element="tns:getSvConfByNameRequest" name="getSvConfByNameRequest"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="getAllSvConfResponse">
        <wsdl:part element="tns:getAllSvConfResponse" name="getAllSvConfResponse"> </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="sv_conf_port">
        <wsdl:operation name="updateSvConf">
            <wsdl:input message="tns:updateSvConfRequest" name="updateSvConfRequest"> </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="getAllSvConf">
            <wsdl:input message="tns:getAllSvConfRequest" name="getAllSvConfRequest"> </wsdl:input>
            <wsdl:output message="tns:getAllSvConfResponse" name="getAllSvConfResponse"> </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="deleteSvConf">
            <wsdl:input message="tns:deleteSvConfRequest" name="deleteSvConfRequest"> </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="getSvConfByName">
            <wsdl:input message="tns:getSvConfByNameRequest" name="getSvConfByNameRequest"> </wsdl:input>
            <wsdl:output message="tns:getSvConfByNameResponse" name="getSvConfByNameResponse"> </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="addSvConf">
            <wsdl:input message="tns:addSvConfRequest" name="addSvConfRequest"> </wsdl:input>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="sv_conf_portSoap11" type="tns:sv_conf_port">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="updateSvConf">
            <soap:operation soapAction=""/>
            <wsdl:input name="updateSvConfRequest">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="getAllSvConf">
            <soap:operation soapAction=""/>
            <wsdl:input name="getAllSvConfRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="getAllSvConfResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="deleteSvConf">
            <soap:operation soapAction=""/>
            <wsdl:input name="deleteSvConfRequest">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="getSvConfByName">
            <soap:operation soapAction=""/>
            <wsdl:input name="getSvConfByNameRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="getSvConfByNameResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="addSvConf">
            <soap:operation soapAction=""/>
            <wsdl:input name="addSvConfRequest">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="sv_conf_portService">
        <wsdl:port binding="tns:sv_conf_portSoap11" name="sv_conf_portSoap11">
            <soap:address location="http://localhost:8088/ws/sv_conf"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
